language: ruby
before_install:
- gem install bundler
- bundle install
after_success:
- script/tag_on_master
script: bundle exec rake book:build
env:
  GITHUB_KEY:
    secure: "l3XdupX6dT48IoTieJXrd7Yx8+KhiR2QYrNrDzT6RKxA7UyXGSP/axsVerg7OjKfIHWZgDJRVzcc2RswE+Xjw9sOY8r2h2q9uCwj8G0EqtFbtgGK0La5LB0euh0tNJN8GLFj1OdSZGY7dWWK88GXeHCua2WSify0V79R4ClIM+s="

deploy:
  provider: releases
  file:
  - progit.epub
  - progit.mobi
  - progit.pdf
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: "l3XdupX6dT48IoTieJXrd7Yx8+KhiR2QYrNrDzT6RKxA7UyXGSP/axsVerg7OjKfIHWZgDJRVzcc2RswE+Xjw9sOY8r2h2q9uCwj8G0EqtFbtgGK0La5LB0euh0tNJN8GLFj1OdSZGY7dWWK88GXeHCua2WSify0V79R4ClIM+s="
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/