name: Release on push to master

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compute tag name
      id: compute-tag
      run: |
        echo Computing next tag number
        LASTPATCH=$(git describe --tags | cut -d- -f1 | cut -d. -f3)
        PATCH=$(($LASTPATCH+1))
        echo "::set-output name=tagname::2.1.${PATCH}"

    - name: Create Tag
      run: |
        git tag ${{ steps.compute-tag.outputs.tagname }}
        git push origin ${{ steps.compute-tag.outputs.tagname }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.compute-tag.outputs.tagname }}
        artifacts: './progit.epub,./progit.mobi,./progit.pdf,./progit.html'
